# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4f8d987c5f77565f7e6fa06ed0b23cce27d2c36d9b7f5eca2775bb82d16007c831d5d760a3d8d792b21452e21a74345edc2c454d06c4562153e67ce69b19c7b

test:
  secret_key_base: 4c472e7dca5c3561b29e71b5448012189f0501f3bfe03dd62b358c3b388f2920cbc7d256a5f350d56b813a6b96fb151983021d8df8ea531fcd6809c75ae40f9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
